get http://localhost:3000/videos

###
POST http://localhost:3000/api/ticket
Content-Type: application/json

{     
    "title": "internet lenta",
    "subTitle": "Internet ficou lenta derrepente",
    "description": "estava pulando corda e rebentou o cabo",
    "observacao": "observando"    
}
###
get http://localhost:3000/api/todo

###
POST http://localhost:3000/api/todo
Content-Type: application/json

{    
    "name":"Brincar", 
    "descricao":"Brincar com a bb",
    "percentual":90
}
###
POST http://localhost:3000/api
Content-Type: application/json

{    
    "name":"Lavar roupa", 
    "descricao":"Lavar toda roupa suja",
    "percentual":100,
    "status": "ABERTO" 
}
###

DELETE http://localhost:3000/api/todo/7
Content-Type: application/json


###
###

PATCH  http://localhost:3000/api/todo/19
Content-Type: application/json

{    
    
    "status": "PAUSADO" 
}

# ATIVO
#   DESATIVADO
#   FAZENDO
#   PAUSADO
#   CANCELADO
#   ABERTO